SELECT 
			TODO_NO, 
			TODO_TITLE, 
			TODO_COMPLETE, 
			TO_CHAR(REG_DATE, 'YYYY-MM-DD HH24:MI:SS') REG_DATE 
		FROM TB_TODO
		WHERE TODO_NO > 0
		ORDER BY TODO_NO ASC;
		
SELECT COUNT(*) 
		FROM TB_TODO
		WHERE TODO_NO > 0
		AND TODO_COMPLETE = 1